# Dependencies

markdown:         kramdown
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            DarkScope
tagline:          '信 省 行'
description:      '新窝，少写干货~~~'

author:
  name:           'DarkScope'
  url:            https://github.com/justdark
  email:			'darkscope.primer@gmail.com'
paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : DarkScope

analytics:
    provider:custom
